seed: 42
exp_name: neumf

recsys:
  dataset_csv: data/raw/ratings.csv
  processed_dir: data/processed
  min_user_interactions: 5
  min_item_interactions: 5
  val_users: 0.15
  test_users: 0.15
  topk: [10, 20]

model:
  name: neumf
  mf_dim: 64
  mlp_layers: [256, 128, 64]
  dropout: 0.10
  user_bias: true
  item_bias: true

optim:
  batch_size: 65536
  lr: 1.0e-3
  weight_decay: 1.0e-5
  epochs: 60
  early_stopping_patience: 3
  early_stopping_metric: auto   # auto | rmse | hr@10 | ndcg@10
  loss: mse                     # mse | approx_ndcg
  approx_ndcg_negatives: 50
  approx_ndcg_temperature: 1.0
  amp: true

log:
  dir: runs
  tensorboard: true
