seed: 42
exp_name: neumf

recsys:
  dataset_csv: data/raw/ratings.csv
  processed_dir: data/processed
  min_user_interactions: 5
  min_item_interactions: 5
  val_users: 0.15
  test_users: 0.15
  topk: [10, 20]

model:
  name: neumf
  mf_dim: 32
  mlp_layers: [128, 64]
  dropout: 0.20
  user_bias: true
  item_bias: true

  # --- features into NeuMF (optional) ---
  item_feat_layers: [32]
  freeze_item_feats: false

optim:
  batch_size: 65536
  lr: 1.0e-3
  weight_decay: 1.0e-5
  epochs: 50
  early_stopping_patience: 3
  amp: true

log:
  dir: runs
  tensorboard: true
