seed: 42
exp_name: anime_exp1

recsys:
  dataset_csv: data/raw/ratings.csv
  processed_dir: data/processed
  min_user_interactions: 5
  min_item_interactions: 5
  val_users: 0.10
  test_users: 0.10
  topk: [10, 20]

model:
  name: neumf         # mf | neumf
  mf_dim: 64
  mlp_layers: [128, 64]
  dropout: 0.10
  user_bias: true
  item_bias: true

  # --- features into NeuMF (optional) ---
  item_feat_layers: [128]   # [] or omit to disable feature tower
  freeze_item_feats: true   # register as buffer; not trainable

optim:
  batch_size: 4096
  lr: 1.0e-3
  weight_decay: 1.0e-5
  epochs: 100
  early_stopping_patience: 3
  amp: true

itemcf:                      # used when model.name == itemcf
  k: 100
  shrink: 50.0
  clip: [1.0, 10.0]

log:
  dir: runs
  tensorboard: false
