seed: 42
exp_name: two_tower_bpr_ft

recsys:
  dataset_csv: data/raw/ratings.csv
  processed_dir: data/processed
  min_user_interactions: 5
  min_item_interactions: 5
  val_users: 0.15
  test_users: 0.15
  topk: [10, 20]

model:
  name: two_tower
  embed_dim: 64
  user_layers: [256, 128, 64]
  item_layers: [256, 128, 64]
  dropout: 0.10
  user_bias: true
  item_bias: true
  item_feature_path: data/processed/outputs/item_feats.npy
  item_feature_layers: [256, 128]
  item_feature_dropout: 0.10
  item_feature_combine: concat

optim:
  batch_size: 4096
  lr: 1.0e-4
  weight_decay: 1.0e-5
  epochs: 20
  early_stopping_patience: 5
  early_stopping_metric: ndcg@10  # ranking metric for BPR fine-tune
  loss: bpr                      # mse | approx_ndcg | bpr
  bpr_negatives: 5
  amp: true

log:
  dir: runs
  tensorboard: true
